name: Prettier Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    name: Check Prettier formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npx prettier --check .
